@extends('layouts.app.master')
@section('title', 'Chart of Accounts')
@section('content')
<div class="page-header"><div class="page-title"><h4 class="fw-bold">Chart of Accounts</h4></div><div class="page-btn"><a href="{{ route('accounts.tree') }}" class="btn btn-secondary">Account Tree</a></div></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if(session('error'))<div class="alert alert-danger">{{ session('error') }}</div>@endif
<div class="card mb-3"><div class="card-header"><h6 class="mb-0">Add Account</h6></div><div class="card-body"><form method="POST" action="{{ route('accounts.store') }}" class="row g-2">@csrf
<div class="col-md-3"><input name="name" class="form-control" placeholder="Account name" required></div>
<div class="col-md-2"><input name="code" class="form-control" placeholder="Code" required></div>
<div class="col-md-2"><select name="account_type" class="form-control" required><option value="asset">Asset</option><option value="liability">Liability</option><option value="equity">Equity</option><option value="income">Income</option><option value="expense">Expense</option></select></div>
<div class="col-md-2"><select name="normal_balance" class="form-control" required><option value="debit">Debit</option><option value="credit">Credit</option></select></div>
<div class="col-md-3"><select name="parent_id" class="form-control"><option value="">No parent</option>@foreach($parents as $parent)<option value="{{ $parent->id }}">{{ $parent->code }} - {{ $parent->name }}</option>@endforeach</select></div>
<div class="col-md-6"><input name="account_subtype" class="form-control" placeholder="Subtype (optional)"></div>
<div class="col-md-5"><input name="notes" class="form-control" placeholder="Notes"></div>
<div class="col-md-1 form-check mt-2"><input class="form-check-input" type="checkbox" checked name="is_active" value="1" id="coa_active"><label class="form-check-label" for="coa_active">Active</label></div>
<div class="col-md-1"><button class="btn btn-primary w-100">Save</button></div>
</form></div></div>
<div class="card"><div class="card-body p-0 table-responsive"><table class="table table-bordered mb-0"><thead class="table-light"><tr><th>Code</th><th>Name</th><th>Type</th><th>Normal</th><th>Parent</th><th>Status</th><th>Action</th></tr></thead><tbody>@foreach($accounts as $account)<tr><td>{{ $account->code }}</td><td>{{ $account->name }} @if($account->is_system)<span class="badge bg-dark ms-1">System</span>@endif</td><td>{{ ucfirst($account->account_type ?: $account->type) }}</td><td>{{ ucfirst($account->normal_balance ?: 'debit') }}</td><td>{{ $account->parent?->name ?: '-' }}</td><td>{{ $account->is_active ? 'Active' : 'Inactive' }}</td><td>@if(!$account->is_system)<form method="POST" action="{{ route('accounts.update', $account) }}" class="row g-1">@csrf @method('PUT')<div class="col-12"><input type="text" name="name" class="form-control form-control-sm" value="{{ $account->name }}" required></div><div class="col-4"><input type="text" name="code" class="form-control form-control-sm" value="{{ $account->code }}" required></div><div class="col-4"><select name="account_type" class="form-control form-control-sm"><option value="asset" {{ ($account->account_type ?: $account->type)==='asset'?'selected':'' }}>Asset</option><option value="liability" {{ ($account->account_type ?: $account->type)==='liability'?'selected':'' }}>Liability</option><option value="equity" {{ ($account->account_type ?: $account->type)==='equity'?'selected':'' }}>Equity</option><option value="income" {{ ($account->account_type ?: $account->type)==='income'?'selected':'' }}>Income</option><option value="expense" {{ ($account->account_type ?: $account->type)==='expense'?'selected':'' }}>Expense</option></select></div><div class="col-4"><select name="normal_balance" class="form-control form-control-sm"><option value="debit" {{ ($account->normal_balance ?: 'debit')==='debit'?'selected':'' }}>Debit</option><option value="credit" {{ ($account->normal_balance ?: 'debit')==='credit'?'selected':'' }}>Credit</option></select></div><div class="col-6"><input type="text" name="account_subtype" class="form-control form-control-sm" value="{{ $account->account_subtype }}" placeholder="Subtype"></div><div class="col-6"><input type="text" name="notes" class="form-control form-control-sm" value="{{ $account->notes }}" placeholder="Notes"></div><div class="col-12"><button class="btn btn-sm btn-warning w-100">Update</button></div></form>@endif</td></tr>@endforeach</tbody></table></div><div class="p-3">{{ $accounts->links() }}</div></div>
@endsection
