@extends('layouts.app.master')

@section('title', 'Stock Ledger')
@section('css')@include('v2.partials.style')@endsection

@section('content')
<div class="v2-wrap">
    <div class="page-header"><div class="page-title v2-title"><h4 class="fw-bold">Stock Ledger Summary</h4></div><div class="v2-actions"><button onclick="window.print()" class="btn btn-primary">Print</button><a href="{{ route('v2.dashboard') }}" class="btn btn-secondary">Exit</a></div></div>
    <div class="card mb-3"><div class="card-body"><form class="row g-2"><div class="col-md-4"><input name="search" value="{{ request('search') }}" class="form-control" placeholder="Search item"></div><div class="col-md-3"><select name="brand_id" class="form-control"><option value="">All Brands</option>@foreach($brands as $brand)<option value="{{ $brand->id }}" @selected(request('brand_id')==$brand->id)>{{ $brand->name }}</option>@endforeach</select></div><div class="col-md-3"><select name="category_id" class="form-control"><option value="">All Categories</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(request('category_id')==$category->id)>{{ $category->name }}</option>@endforeach</select></div><div class="col-md-2"><button class="btn btn-secondary w-100">Search</button></div><div class="col-md-2"><label class="form-check"><input type="checkbox" name="zeroed" value="1" class="form-check-input"> Zeroed Stock</label></div><div class="col-md-3"><label class="form-check"><input type="checkbox" name="non_zeroed" value="1" class="form-check-input"> Non-Zeroed Stock</label></div></form></div></div>
    <div class="card"><div class="table-responsive"><table class="table table-bordered mb-0"><thead class="table-light"><tr><th>Item Description</th><th>Item Code</th><th>Qty In</th><th>Qty Out</th><th>Balance Qty</th><th>Packing</th><th>Cost</th><th>Stock Amount</th><th>Reports</th></tr></thead><tbody>@forelse($items as $item)@php($qtyIn=(float)$item->stockMovements()->sum('qty_in'))@php($qtyOut=(float)$item->stockMovements()->sum('qty_out'))<tr><td>{{ $item->description }}</td><td>{{ $item->code }}</td><td>{{ number_format($qtyIn,3) }}</td><td>{{ number_format($qtyOut,3) }}</td><td>{{ number_format($item->balance_qty,3) }}</td><td>{{ $item->packing }}</td><td>@can('v2 cost visible'){{ number_format((float)$item->cost,2) }}@else Hidden @endcan</td><td>@can('v2 cost visible'){{ number_format($item->balance_qty * (float)$item->cost,2) }}@else Hidden @endcan</td><td class="v2-actions"><a class="btn btn-sm btn-info" href="{{ route('v2.stock-ledger.statement', [$item, 'statement']) }}">Statement</a><a class="btn btn-sm btn-light" href="{{ route('v2.stock-ledger.statement', [$item, 'monthly']) }}">Monthly</a><a class="btn btn-sm btn-light" href="{{ route('v2.stock-ledger.statement', [$item, 'valuation-rate']) }}">Valuation</a><a class="btn btn-sm btn-light" href="{{ route('v2.stock-ledger.statement', [$item, 'profit-loss']) }}">Profit/Loss</a></td></tr>@empty<tr><td colspan="9" class="text-center">No stock found.</td></tr>@endforelse</tbody></table></div><div class="p-3">{{ $items->links() }}</div></div>
</div>
@endsection
