@extends('layouts.app.master')

@section('title', ($types[$type] ?? $type) . ' Ledger')
@section('css')@include('v2.partials.style')@endsection

@section('content')
<div class="v2-wrap">
    <div class="page-header"><div class="page-title v2-title"><h4 class="fw-bold">{{ $types[$type] ?? $type }} Ledger Summary</h4></div><div class="v2-actions"><button onclick="window.print()" class="btn btn-primary">Print</button><a href="{{ route('v2.dashboard') }}" class="btn btn-secondary">Exit</a></div></div>
    <div class="card mb-3"><div class="card-body"><form class="row g-2"><div class="col-md-4"><input name="search" value="{{ request('search') }}" class="form-control" placeholder="Search"></div><div class="col-md-2"><label class="form-check mt-2"><input type="checkbox" name="zeroed" value="1" @checked(request('zeroed')) class="form-check-input"> Zeroed</label></div><div class="col-md-3"><label class="form-check mt-2"><input type="checkbox" name="non_zeroed" value="1" @checked(request('non_zeroed')) class="form-check-input"> Non-Zeroed</label></div><div class="col-md-2"><button class="btn btn-secondary w-100">Search</button></div></form></div></div>
    <div class="card"><div class="table-responsive"><table class="table table-bordered mb-0"><thead class="table-light"><tr><th>Account Name</th><th>Code</th><th>Balance</th><th>Telephone</th><th>Actions</th></tr></thead><tbody>@forelse($accounts as $account)<tr><td>{{ $account->name }}</td><td>{{ $account->code }}</td><td>PKR {{ number_format($account->balance,2) }}</td><td>{{ $account->detail?->phone }}</td><td class="v2-actions"><a class="btn btn-sm btn-info" href="{{ route('v2.ledgers.detail', [$account, 'ledger']) }}">View Ledger</a><a class="btn btn-sm btn-light" href="{{ route('v2.ledgers.detail', [$account, 'statement']) }}">Statement</a><a class="btn btn-sm btn-light" href="{{ route('v2.ledgers.detail', [$account, 'detailed-analysis']) }}">Detailed Analysis</a><a class="btn btn-sm btn-light" href="{{ route('v2.ledgers.detail', [$account, 'monthly-analysis']) }}">Monthly</a><a class="btn btn-sm btn-light" href="{{ route('v2.ledgers.detail', [$account, 'aging-sales']) }}">Sales Aging</a><a class="btn btn-sm btn-light" href="{{ route('v2.ledgers.detail', [$account, 'aging-purchase']) }}">Purchase Aging</a><a class="btn btn-sm btn-light" href="{{ route('v2.ledgers.detail', [$account, 'debit-credit']) }}">Dr/Cr</a><a class="btn btn-sm btn-light" href="{{ route('v2.ledgers.detail', [$account, 'cash-credit']) }}">Cash/Credit</a></td></tr>@empty<tr><td colspan="5" class="text-center">No accounts found.</td></tr>@endforelse</tbody></table></div><div class="p-3">{{ $accounts->links() }}</div></div>
</div>
@endsection
